version: '3.8'

services:
  # -----------------------------------------------------------------
  # 1. BASE DE DATOS MYSQL
  # -----------------------------------------------------------------
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: walletdb
    volumes:
      - db_data:/var/lib/mysql

  # -----------------------------------------------------------------
  # 2. SERVICIO DB (NestJS - service-db-layer)
  # -----------------------------------------------------------------
  service-db-layer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: service-db-layer
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PREFIX: api/v1
      SERVER_PORT: 3000
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: walletdb
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_SSL: false
      DB_AUTO_LOAD_MODELS: true
      DB_SYNCHRONIZE: false
      DB_LOGGING: false
      ALLOWED_ORIGINS: http://api-gateway:4000
      JWT_SECRET: c3Ryb25nLXNlY3JldC1mb3ItZGV2ZWxvcG1lbnQtMTIzNDU2Nzg5MA==
      JWT_EXPIRES_IN: 1h
      MAIL_PORT: 587
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_USER: 49dc76c3cb41dc
      MAIL_PASSWORD: 30cbd2d1d815ac
      MAIL_FROM: noreply@example.com
    depends_on:
      - mysql-db

  # -----------------------------------------------------------------
  # 3. API GATEWAY (Express - api-gateway)
  # -----------------------------------------------------------------
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      APP_GATEWAY_URL: http://api-gateway
      APP_GATEWAY_PORT: 4000
      APP_SERVICE_DB_LAYER_URL: http://service-db-layer:3000
      APP_WALLET_CLIENT_URL: http://wallet-client:8080
      ALLOWED_ORIGINS: http://wallet-client:8080,http://localhost:8080
    depends_on:
      - service-db-layer

  # -----------------------------------------------------------------
  # 4. CLIENTE WEB (React/Vite - wallet-client)
  # -----------------------------------------------------------------
  wallet-client:
    build:
      context: ../wallet-client
      dockerfile: Dockerfile
      args:
        VITE_APP_API_GATEWAY_URL: http://api-gateway:4000/api/v1
    container_name: wallet-client
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway

volumes:
  db_data:
